FROM jenkins/jenkins:2.344
USER root

RUN apt-get update && apt-get install -qq -f -y make git openjdk-17-jdk

# Realiza a instalação dos certificados
RUN keytool -J-Djava.net.useSystemProxies=true -printcert -rfc -sslserver updates.jenkins.io:443 > /tmp/updates.jenkins.io.pem && \
    keytool -importcert -file /tmp/updates.jenkins.io.pem -alias updates.jenkins.io -noprompt -storepass changeit -keystore ${JAVA_HOME}/lib/security/cacerts

# backup
RUN mkdir /srv/backup && chown jenkins:jenkins /srv/backup

USER jenkins

# remover wizard
RUN echo latest > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state
RUN echo latest > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion

# instalar plugins no jenkins
COPY --chown=jenkins:jenkins plugins-2_344.txt /usr/share/jenkins/ref/plugins.txt
#RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64

# copiando o backup das configurações para a imagem
COPY --chown=jenkins:jenkins config_jenkins /var/jenkins_home


## https://stackoverflow.com/questions/53669151/java-11-application-as-lightweight-docker-image/57145029#57145029
